FROM alpine:latest

RUN apk add --no-cache \
    curl \
    jq

RUN curl -L https://github.com/stripe/stripe-cli/releases/download/v1.8.7/stripe_1.8.7_linux_x86_64.tar.gz | tar -xz -C /usr/local/bin

ENTRYPOINT ["stripe"]
