name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start containers
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: |
          # Example of waiting for a service on port 3000 to be ready
          while ! nc -z localhost 3000; do
            echo "Waiting for the service to start...";
            sleep 5;
          done
          echo "Service is up and running!"

      - name: Run tests
        run: |
          cd backend
          ls
          npm run test
      

