name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start containers
        run: docker-compose up -d

      - name: Change directory to backend
        working-directory: ./backend

      - name: Run tests
        run: npm run test

      

