name: Backend

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start containers
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 120;

      - name: Run tests
        run: docker-compose exec node npm run test
      

