name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: app
        ports:
          - 5432:5432

    env:
      MONGO_URL: mongodb://localhost:27017
      DATABASE_URL: postgres://root:password@localhost:5432/app
      JWT_SECRET: secret

    strategy:
      matrix:
        command: [ 'npm run dev', 'npm run build' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Build/Dev
        working-directory: ./backend
        run: ${{ matrix.command }}

      - name: Run tests
        working-directory: ./backend
        run: npm test
